name: oli_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  http: ^1.1.0
  flutter_secure_storage: ^10.0.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  collection: ^1.17.0

  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  socket_io_client: ^3.1.3
  shared_preferences: ^2.5.4
  share_plus: ^10.1.0
  geolocator: ^13.0.1
  geocoding: ^2.1.0 # Added for reverse geocoding
  geolocator_web: ^4.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.0
  record: ^5.0.0
  audioplayers: ^5.2.0
  permission_handler: ^11.0.0
  flutter_contacts: ^1.1.9
  path_provider: ^2.1.1
  easy_localization: ^3.0.7
  local_auth: ^2.3.0
  qr_flutter: ^4.1.0
  video_player: ^2.9.2
  mobile_scanner: ^3.5.5
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/chat_bg.png
    - assets/images/chat_bg_new.png
    - assets/images/services_icon.png
    - assets/images/fire_bg.png
    - assets/images/super_offers_bg.jpg
    - assets/images/oli_logo_refresh.png
    - assets/images/megaphone_icon.png
    - assets/images/drc flag.png
    - assets/images/ads/
    - assets/images/categories/
    - assets/images/services/
    - assets/images/operators/
    - assets/translations/

  fonts:
    - family: olive_palm
      fonts:
        - asset: assets/fonts/olive_palm.otf
